spring:
  application:
    name: email-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: mory.keita@marielsoftwares.com
    password: iods bmje dnes rult
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  kafka:
    bootstrap-servers: localhost:29092
    admin.auto-create: true
    consumer:
      group-id: email-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      spring.json.trusted.packages: '*'
